### ISSUE TITLE
Akamai Short Cuts

### ISSUE THREAD

**Issue by usdafsajeff** [usdafsajeff/fsasoftlaunch#19]
Need to check all short cuts as http://www.fsa.usda.gov/notices is not working.

**Comment by MartinLeborgne** [comment]
All Akamai shortcuts are working.  However, there are several shortcuts being managed by NITC (such as states) that are not working.  States are OK.  Getting full  list of NITC managed shortcuts to then use in a filter in Akamai.

**Comment by MartinLeborgne** [comment]
Akamai push to do this filter was started at 1:30.  

This is pending an hour long Akamai push to prod....pending

**Comment by MartinLeborgne** [comment]
Implemented and fixed in Aka v 186.
Can be closed.

**Comment by usdafsajeff** [comment]
Still not working. http://www.fsa.usda.gov/dafl takes you to the old farm loans page.

http://www.fsa.usda.gov/pricesupport going to old site also.

http://www.fsa.usda.gov/microloans going to old site also.
