### ISSUE TITLE
DACO- Anchor tags not going to appropriate section of page on Archived Commodity Requirements page

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#33]
www.fsa.usda.gov in IE 9

http://www.fsa.usda.gov/programs-and-services/commodity-operations/procurement-and-sales/archived-contract-terms/archived-commodity-requirements/index

Anchor links below are not moving to the proper section of page

Bulk Commodity

Dairy

Dairy Price Support

Domestic

Export

**Comment by angelamathews** [comment]
WSO tech team said this is an ENHANCEMENT that will be updated later...

**Comment by sonjaeasley** [comment]
This is fixed. It should be working now.

**Comment by angelamathews** [comment]
There are two problems. First, the Domestic anchor goes to Archived Dairy Price Support USDA-1  instead of Archived Domestic Commodity Requirements..Also, the Commodity Purchase Announcements and Amendments (prior to Sep 1, 2005) cuts off half of the title when the anchor sends you to that section. Can we fix these? Thanks

**Comment by angelamathews** [comment]
Has it been published? I am seeing the same problems in IE 9. It isn't fixed yet.

**Comment by angelamathews** [comment]
Verified that anchor tags are now directed to the appropriate section.
