### ISSUE TITLE
Site Map: Disaster Assistance URLs different than working ones- Page Not Found

### ISSUE THREAD

**Issue by angelamathews** [usdafsajeff/fsasoftlaunch#57]
IE 9

On the site map: http://www.fsa.usda.gov/help/site-map the Disaster links are also different than the working ones: 

Good link: http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/emergency-assist-for-livestock-honey-bees-fish/index  Bad link has -elap at the end

Bad link: http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/emergency-assist-for-livestock-honey-bees-fish-elap/index

These are also broken: 
Bad: http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/emergency-forest-restoration-program-efrp/index 

Good; http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/emergency-forest-restoration/index  Extra -program-efp on Bad link above

Others: 
http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/livestock-forage-program-lfp/index

http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/livestock-indemnity-program-lip/index

http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/noninsured-crop-disaster-assistance-program-nap/index

http://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/tree-assistance-program-tap/index

**Comment by psleman** [comment]
I have fixed the broken links under the Disaster Assiatnce programs heading on the site map

**Comment by angelamathews** [comment]
Have these changes been published? I still see NAP, EFRP, LIP as broken and Disaster Eligibility as goign to Contact Us...Thanks

**Comment by psleman** [comment]
I fixed NAP, EFRP, LIP, they have been published.

One question: Is the correct Url for Disaster eligibility: http://www.fsa.usda.gov/FSA/webapp?area=home&subject=diap&topic=daet? If yes it redirects back to the Disaster Assistance programs home page. Also the links in between the Disaster Assistance Tool link (Archived Programs(http://www.fsa.usda.gov/FSA/webapp?area=home&subject=diap&topic=dar) and Disaster Payment maps(http://www.fsa.usda.gov/FSA/webapp?area=home&subject=diap&topic=dpm)) redirect back to the homepage for Disaster Assistance programs. Thank you.

Paul

**Comment by angelamathews** [comment]
Verified links have been corrected on Disaster section of Site Map. Thanks

**Comment by MartinLeborgne** [comment]
Thank you, All...Closing
